// frontend-shop/src/app/shared/components/product-card/product-card.component.ts
import { Component, input, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { CurrencyPipe } from '@angular/common';
import { type Product, CATEGORY_LABELS } from '../../../core/models/product.model';
import { CartService } from '../../../core/services/cart.service';

@Component({
  selector: 'app-product-card',
  standalone: true,
  imports: [RouterLink, MatButtonModule, MatIconModule, MatChipsModule, CurrencyPipe],
  templateUrl: './product-card.component.html',
})
export class ProductCardComponent {
  readonly product = input.required<Product>();

  private readonly cartService = inject(CartService);
  readonly categoryLabels = CATEGORY_LABELS;

  get available(): number {
    const p = this.product();
    return p.stockQuantity - p.reservedQuantity;
  }

  get categoryLabel(): string {
    return CATEGORY_LABELS[this.product().category] ?? this.product().category;
  }

  async addToCart(): Promise<void> {
    await this.cartService.addItem(this.product().id, 1);
  }
}

<div class="group relative overflow-hidden rounded-xl border border-gray-200 bg-white transition-all hover:shadow-lg hover:-translate-y-1">
  <!-- Promo badge -->
  @if (product().promotionPercentage > 0) {
    <span class="absolute top-3 left-3 z-10 bg-red-500 text-white text-xs font-bold px-2 py-0.5 rounded-full">
      -{{ product().promotionPercentage }}%
    </span>
  }

  <!-- Image -->
  <a [routerLink]="['/products', product().slug]">
    <div class="aspect-square overflow-hidden p-4 bg-gray-50">
      <img [src]="product().imageUrl" [alt]="product().name"
           class="h-full w-full object-contain transition-transform group-hover:scale-105"
           loading="lazy" />
    </div>
  </a>

  <!-- Content -->
  <div class="p-4">
    <div class="flex items-start justify-between gap-2 mb-2">
      <span class="inline-block text-xs font-medium px-2 py-0.5 bg-gray-100 text-gray-700 rounded-full">
        {{ categoryLabel }}
      </span>
      @if (available < 10 && available > 0) {
        <span class="inline-block text-xs font-medium px-2 py-0.5 bg-red-100 text-red-700 rounded-full">
          Plus que {{ available }}
        </span>
      }
    </div>

    <a [routerLink]="['/products', product().slug]">
      <h3 class="font-semibold text-sm line-clamp-2 hover:text-blue-600 transition-colors text-gray-900">
        {{ product().name }}
      </h3>
    </a>
    <p class="mt-1 text-xs text-gray-500 line-clamp-1">{{ product().shortDesc }}</p>

    <div class="mt-3 flex items-center justify-between">
      <!-- Price -->
      <div>
        @if (product().promotionPercentage > 0) {
          <div class="flex flex-col">
            <span class="text-sm font-bold text-gray-900">
              {{ product().discountedPrice | currency:'EUR':'symbol':'1.0-0':'fr' }}
            </span>
            <span class="text-xs text-gray-400 line-through">
              {{ product().price | currency:'EUR':'symbol':'1.0-0':'fr' }}
            </span>
          </div>
        } @else {
          <span class="text-sm font-bold text-gray-900">
            {{ product().price | currency:'EUR':'symbol':'1.0-0':'fr' }}
          </span>
        }
      </div>

      <button mat-stroked-button color="primary" [disabled]="available <= 0" (click)="addToCart()">
        <mat-icon class="text-sm">shopping_cart</mat-icon>
        {{ available > 0 ? 'Ajouter' : 'Rupture' }}
      </button>
    </div>
  </div>
</div>

// frontend-shop/src/components/product/ProductCard.tsx
import { Link } from 'react-router-dom';
import type { Product } from '@/lib/api';
import { useCartStore } from '@/stores/cart-store';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { ShoppingCart } from 'lucide-react';

const CATEGORY_LABELS: Record<string, string> = {
  MACBOOK_AIR: 'MacBook Air',
  MACBOOK_PRO: 'MacBook Pro',
  IMAC: 'iMac',
  MAC_MINI: 'Mac Mini',
  MAC_STUDIO: 'Mac Studio',
  MAC_PRO: 'Mac Pro',
};

interface ProductCardProps {
  readonly product: Product;
}

export function ProductCard({ product }: ProductCardProps) {
  const { addItem } = useCartStore();
  const available = product.stockQuantity - product.reservedQuantity;

  const handleAddToCart = () => {
    addItem(product.id, 1);
  };

  return (
    <Card className="group overflow-hidden transition-all hover:shadow-lg hover:-translate-y-1">
      <Link to={`/products/${product.slug}`}>
        <div
          className="aspect-square overflow-hidden rounded-t-xl p-4"
          style={{ backgroundColor: product.backgroundColor, marginTop: 'calc(var(--card-spacing) * -1)' }}
        >
          <img
            src={product.imageUrl}
            alt={product.name}
            className="h-full w-full object-contain transition-transform group-hover:scale-105"
            loading="lazy"
          />
        </div>
      </Link>
      <CardContent className="p-4">
        <div className="flex items-start justify-between gap-2">
          <Badge variant="secondary" className="text-xs">
            {CATEGORY_LABELS[product.category] ?? product.category}
          </Badge>
          {available < 10 && available > 0 && (
            <Badge variant="destructive" className="text-xs">
              Plus que {available}
            </Badge>
          )}
        </div>
        <Link to={`/products/${product.slug}`}>
          <h3 className="mt-2 font-semibold text-sm line-clamp-2 hover:text-primary transition-colors">
            {product.name}
          </h3>
        </Link>
        <p className="mt-1 text-xs text-muted-foreground line-clamp-1">
          {product.shortDesc}
        </p>
        <div className="mt-3 flex items-center justify-between">
          <span className="text-lg font-bold">
            {product.price.toLocaleString('fr-FR', { style: 'currency', currency: 'EUR' })}
          </span>
          <Button size="sm" variant="outline" disabled={available <= 0} onClick={handleAddToCart}>
            <ShoppingCart className="mr-1 h-4 w-4" />
            {available > 0 ? 'Ajouter' : 'Rupture'}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
