// frontend-shop/src/components/layout/ShopHeader.tsx
import { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from 'react-oidc-context';
import { ShoppingCart, Apple, User, LogOut, Menu, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useCartStore } from '@/stores/cart-store';
import { CartDrawer } from '@/components/cart/CartDrawer';

export function ShopHeader() {
  const auth = useAuth();
  const { itemCount } = useCartStore();
  const [cartOpen, setCartOpen] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [badgeBounce, setBadgeBounce] = useState(false);
  const prevCountRef = useRef(0);
  const count = itemCount();

  useEffect(() => {
    if (count > prevCountRef.current && prevCountRef.current >= 0) {
      setBadgeBounce(true);
      const timer = setTimeout(() => setBadgeBounce(false), 300);
      prevCountRef.current = count;
      return () => clearTimeout(timer);
    }
    prevCountRef.current = count;
  }, [count]);

  return (
    <>
      <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container mx-auto flex h-16 items-center justify-between px-4">
          <Link to="/" className="flex items-center gap-2 font-bold text-xl">
            <Apple className="h-6 w-6" />
            <span>MacMarket</span>
          </Link>

          <nav className="hidden md:flex items-center gap-6">
            <Link to="/products" className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors">
              Catalogue
            </Link>
            {auth.isAuthenticated && (
              <Link to="/orders" className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors">
                Mes commandes
              </Link>
            )}
          </nav>

          <div className="flex items-center gap-3">
            <button
              onClick={() => setMobileMenuOpen(prev => !prev)}
              className="inline-flex items-center justify-center rounded-lg h-8 w-8 hover:bg-muted transition-colors md:hidden"
              aria-label="Menu"
            >
              {mobileMenuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
            </button>
            <button
              onClick={() => setCartOpen(true)}
              className="relative inline-flex items-center justify-center rounded-lg h-8 w-8 hover:bg-muted transition-colors"
            >
              <ShoppingCart className="h-5 w-5" />
              {count > 0 && (
                <span className={`absolute -top-1 -right-1 h-5 w-5 rounded-full bg-primary text-primary-foreground text-xs flex items-center justify-center font-bold transition-transform duration-300 ${badgeBounce ? 'scale-125' : 'scale-100'}`}>
                  {count > 9 ? '9+' : count}
                </span>
              )}
            </button>

            {auth.isAuthenticated ? (
              <div className="flex items-center gap-2">
                <Link to="/account" className="inline-flex items-center gap-1.5 rounded-lg px-3 h-8 text-sm hover:bg-muted transition-colors">
                  <User className="h-4 w-4" />
                  <span className="hidden sm:inline">{auth.user?.profile?.name || 'Compte'}</span>
                </Link>
                <Button variant="ghost" size="sm" onClick={() => auth.signoutRedirect()} className="text-muted-foreground">
                  <LogOut className="h-4 w-4" />
                </Button>
              </div>
            ) : (
              <Button variant="outline" size="sm" onClick={() => auth.signinRedirect()}>
                Se connecter
              </Button>
            )}
          </div>
        </div>
      </header>

      {mobileMenuOpen && (
        <div className="border-b bg-background md:hidden">
          <nav className="container mx-auto flex flex-col px-4 py-3 gap-2">
            <Link
              to="/products"
              onClick={() => setMobileMenuOpen(false)}
              className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors py-2"
            >
              Catalogue
            </Link>
            {auth.isAuthenticated && (
              <Link
                to="/orders"
                onClick={() => setMobileMenuOpen(false)}
                className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors py-2"
              >
                Mes commandes
              </Link>
            )}
          </nav>
        </div>
      )}

      <CartDrawer open={cartOpen} onClose={() => setCartOpen(false)} />
    </>
  );
}

// frontend-shop/src/app/shared/components/header/shop-header.component.ts
import { Component, inject, signal, computed, OnInit } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { CartService } from '../../../core/services/cart.service';
import { CartDrawerService } from '../cart-drawer/cart-drawer.service';

@Component({
  selector: 'app-shop-header',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, MatButtonModule, MatIconModule],
  templateUrl: './shop-header.component.html',
})
export class ShopHeaderComponent implements OnInit {
  private readonly oidc = inject(OidcSecurityService);
  private readonly cartService = inject(CartService);
  private readonly cartDrawerService = inject(CartDrawerService);

  readonly isAuthenticated = signal(false);
  readonly userName = signal<string>('');
  readonly mobileMenuOpen = signal(false);
  readonly itemCount = this.cartService.itemCount;

  ngOnInit(): void {
    this.oidc.isAuthenticated$.subscribe(({ isAuthenticated }) => {
      this.isAuthenticated.set(isAuthenticated);
    });
    this.oidc.userData$.subscribe(({ userData }) => {
      if (userData) {
        this.userName.set((userData['name'] as string) || (userData['preferred_username'] as string) || '');
      }
    });
  }

  openCart(): void {
    this.cartDrawerService.open();
  }

  toggleMobileMenu(): void {
    this.mobileMenuOpen.update((v) => !v);
  }

  closeMobileMenu(): void {
    this.mobileMenuOpen.set(false);
  }

  login(): void {
    this.oidc.authorize();
  }

  logout(): void {
    const keycloakUrl = 'http://localhost:8180';
    const appUrl = window.location.origin;
    this.oidc.logoffAndRevokeTokens().subscribe(() => {
      const logoutUrl = new URL(`${keycloakUrl}/realms/macmarket/protocol/openid-connect/logout`);
      logoutUrl.searchParams.set('client_id', 'macmarket-shop');
      logoutUrl.searchParams.set('post_logout_redirect_uri', appUrl);
      window.location.href = logoutUrl.toString();
    });
  }
}

<header class="sticky top-0 z-50 border-b border-gray-200 bg-white/95 backdrop-blur">
  <div class="container mx-auto flex h-16 items-center justify-between px-4">
    <!-- Logo -->
    <a routerLink="/" class="flex items-center gap-2 font-bold text-xl text-gray-900 hover:text-gray-700">
      <mat-icon>laptop_mac</mat-icon>
      <span>MacMarket</span>
    </a>

    <!-- Navigation desktop -->
    <nav class="hidden md:flex items-center gap-6">
      <a routerLink="/products"
         class="text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors">
        Catalogue
      </a>
      @if (isAuthenticated()) {
        <a routerLink="/orders"
           class="text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors">
          Mes commandes
        </a>
      }
    </nav>

    <!-- Actions -->
    <div class="flex items-center gap-2">
      <!-- Menu mobile -->
      <button class="md:hidden p-2 rounded-lg hover:bg-gray-100 transition-colors"
              (click)="toggleMobileMenu()"
              aria-label="Menu">
        <mat-icon>{{ mobileMenuOpen() ? 'close' : 'menu' }}</mat-icon>
      </button>

      <!-- Cart button -->
      <button class="relative p-2 rounded-lg hover:bg-gray-100 transition-colors"
              (click)="openCart()"
              aria-label="Mon panier">
        <mat-icon>shopping_cart</mat-icon>
        @if (itemCount() > 0) {
          <span class="absolute -top-1 -right-1 h-5 w-5 rounded-full bg-blue-600 text-white text-xs flex items-center justify-center font-bold">
            {{ itemCount() > 9 ? '9+' : itemCount() }}
          </span>
        }
      </button>

      <!-- Auth -->
      @if (isAuthenticated()) {
        <a routerLink="/account"
           class="hidden sm:flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm hover:bg-gray-100 transition-colors">
          <mat-icon class="text-base">person</mat-icon>
          <span>{{ userName() || 'Compte' }}</span>
        </a>
        <button mat-icon-button (click)="logout()" title="Se déconnecter" class="text-gray-500">
          <mat-icon>logout</mat-icon>
        </button>
      } @else {
        <button mat-stroked-button (click)="login()" class="text-sm">
          Se connecter
        </button>
      }
    </div>
  </div>
</header>

<!-- Menu mobile -->
@if (mobileMenuOpen()) {
  <div class="border-b border-gray-200 bg-white md:hidden">
    <nav class="container mx-auto flex flex-col px-4 py-3 gap-2">
      <a routerLink="/products" (click)="closeMobileMenu()"
         class="text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors py-2">
        Catalogue
      </a>
      @if (isAuthenticated()) {
        <a routerLink="/orders" (click)="closeMobileMenu()"
           class="text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors py-2">
          Mes commandes
        </a>
      }
    </nav>
  </div>
}
