// frontend-admin/src/components/layout/AdminLayout.tsx
import { useState, useCallback } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useAuth } from 'react-oidc-context';
import { hasRole, getUserRoles } from '@/lib/auth';
import {
  LayoutDashboard, Package, ShoppingCart, Users,
  TrendingUp, BarChart3, UserCheck, ClipboardList,
  LogOut, Shield, Menu, X,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { Breadcrumb } from '@/components/shared/Breadcrumb';

const managerNav = [
  { to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { to: '/inventory', label: 'Inventaire', icon: Package },
  { to: '/orders', label: 'Commandes', icon: ShoppingCart },
  { to: '/customers', label: 'Clients', icon: Users },
] as const;

const adminNav = [
  { to: '/stats/revenue', label: 'Revenus', icon: TrendingUp },
  { to: '/stats/products', label: 'Produits', icon: BarChart3 },
  { to: '/stats/customers', label: 'Clients', icon: UserCheck },
  { to: '/stats/orders', label: 'Commandes', icon: ClipboardList },
] as const;

export function AdminLayout({ children }: { readonly children: React.ReactNode }) {
  const auth = useAuth();
  const location = useLocation();
  const isAdmin = hasRole(auth.user, 'ADMIN');
  const roles = getUserRoles(auth.user).filter(r => !r.startsWith('default-'));
  const [mobileOpen, setMobileOpen] = useState(false);

  const closeMobileSidebar = useCallback(() => {
    setMobileOpen(false);
  }, []);

  const sidebarContent = (
    <>
      <div className="p-4 border-b border-slate-700">
        <Link to="/dashboard" className="flex items-center gap-2 font-bold text-lg" onClick={closeMobileSidebar}>
          <Shield className="h-5 w-5 text-blue-400" />
          MacMarket Admin
        </Link>
      </div>

      <nav className="flex-1 p-3 space-y-1">
        {managerNav.map((item) => (
          <Link
            key={item.to}
            to={item.to}
            onClick={closeMobileSidebar}
            className={cn(
              'flex items-center gap-3 px-3 py-2 rounded-lg text-sm transition-colors',
              location.pathname === item.to || location.pathname.startsWith(item.to + '/')
                ? 'bg-slate-700 text-white'
                : 'text-slate-400 hover:text-white hover:bg-slate-800'
            )}
          >
            <item.icon className="h-4 w-4" />
            {item.label}
          </Link>
        ))}

        {isAdmin && (
          <>
            <div className="pt-4 pb-1 px-3">
              <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">
                Statistiques
              </span>
            </div>
            {adminNav.map((item) => (
              <Link
                key={item.to}
                to={item.to}
                onClick={closeMobileSidebar}
                className={cn(
                  'flex items-center gap-3 px-3 py-2 rounded-lg text-sm transition-colors',
                  location.pathname === item.to
                    ? 'bg-slate-700 text-white'
                    : 'text-slate-400 hover:text-white hover:bg-slate-800'
                )}
              >
                <item.icon className="h-4 w-4" />
                {item.label}
              </Link>
            ))}
          </>
        )}
      </nav>

      <div className="p-3 border-t border-slate-700">
        <div className="flex items-center gap-3 px-3 py-2">
          <div className="h-8 w-8 rounded-full bg-slate-700 flex items-center justify-center text-xs font-bold">
            {(auth.user?.profile?.name || '?')[0].toUpperCase()}
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-sm truncate">{auth.user?.profile?.email}</p>
            <p className="text-xs text-slate-400">{roles.join(', ')}</p>
          </div>
          <button
            onClick={() => auth.signoutRedirect()}
            className="text-slate-400 hover:text-white transition-colors"
          >
            <LogOut className="h-4 w-4" />
          </button>
        </div>
      </div>
    </>
  );

  return (
    <div className="flex min-h-screen">
      {/* Desktop sidebar */}
      <aside className="hidden md:flex w-64 bg-slate-900 text-white flex-col">
        {sidebarContent}
      </aside>

      {/* Mobile backdrop */}
      {mobileOpen && (
        <div
          className="fixed inset-0 z-40 bg-black/50 md:hidden"
          onClick={closeMobileSidebar}
          aria-hidden="true"
        />
      )}

      {/* Mobile sidebar */}
      <aside
        className={cn(
          'fixed inset-y-0 left-0 z-50 w-64 bg-slate-900 text-white flex flex-col transition-transform duration-200 ease-in-out md:hidden',
          mobileOpen ? 'translate-x-0' : '-translate-x-full'
        )}
      >
        <button
          onClick={closeMobileSidebar}
          className="absolute top-4 right-4 text-slate-400 hover:text-white transition-colors"
          aria-label="Fermer le menu"
        >
          <X className="h-5 w-5" />
        </button>
        {sidebarContent}
      </aside>

      <div className="flex-1 flex flex-col">
        {/* Mobile header with hamburger */}
        <header className="md:hidden flex items-center gap-3 bg-white border-b px-4 py-3">
          <button
            onClick={() => setMobileOpen(true)}
            className="text-slate-600 hover:text-slate-900 transition-colors"
            aria-label="Ouvrir le menu"
          >
            <Menu className="h-5 w-5" />
          </button>
          <div className="flex items-center gap-2 font-bold text-sm">
            <Shield className="h-4 w-4 text-blue-500" />
            MacMarket Admin
          </div>
        </header>

        <main className="flex-1 bg-slate-50 p-6 overflow-auto">
          <Breadcrumb />
          {children}
        </main>
      </div>
    </div>
  );
}

// frontend-admin/src/app/shared/components/admin-layout/admin-layout.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet, Router } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { combineLatest } from 'rxjs';
import { getAdminRoles } from '../../../core/guards/admin.guard';

interface NavItem {
  readonly path: string;
  readonly label: string;
  readonly icon: string;
  readonly adminOnly?: boolean;
}

const NAV_ITEMS: readonly NavItem[] = [
  { path: '/dashboard', label: 'Tableau de bord', icon: 'dashboard' },
  { path: '/orders', label: 'Commandes', icon: 'receipt_long' },
  { path: '/inventory', label: 'Inventaire', icon: 'inventory_2' },
  { path: '/customers', label: 'Clients', icon: 'people' },
  { path: '/stats', label: 'Statistiques', icon: 'bar_chart', adminOnly: true },
];

@Component({
  selector: 'app-admin-layout',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, RouterOutlet, MatIconModule, MatButtonModule],
  templateUrl: './admin-layout.component.html',
})
export class AdminLayoutComponent implements OnInit {
  private readonly oidc = inject(OidcSecurityService);
  private readonly router = inject(Router);

  readonly isAuthenticated = signal(false);
  readonly userName = signal('');
  readonly isAdmin = signal(false);
  readonly sidebarOpen = signal(false);
  readonly navItems = NAV_ITEMS;

  ngOnInit(): void {
    combineLatest([this.oidc.isAuthenticated$, this.oidc.userData$]).subscribe(
      ([{ isAuthenticated }, { userData }]) => {
        this.isAuthenticated.set(isAuthenticated);
        if (userData) {
          this.userName.set((userData['name'] as string) || (userData['preferred_username'] as string) || '');
          const roles = getAdminRoles(userData);
          this.isAdmin.set(roles.includes('ADMIN'));
        }
      }
    );
  }

  visibleNav(): readonly NavItem[] {
    return this.navItems.filter((n) => !n.adminOnly || this.isAdmin());
  }

  toggleSidebar(): void {
    this.sidebarOpen.update((v) => !v);
  }

  closeSidebar(): void {
    this.sidebarOpen.set(false);
  }

  logout(): void {
    const keycloakUrl = 'http://localhost:8180';
    const appUrl = window.location.origin;
    this.oidc.logoffAndRevokeTokens().subscribe(() => {
      const url = new URL(`${keycloakUrl}/realms/macmarket/protocol/openid-connect/logout`);
      url.searchParams.set('client_id', 'macmarket-admin');
      url.searchParams.set('post_logout_redirect_uri', appUrl);
      window.location.href = url.toString();
    });
  }
}

<div class="min-h-screen flex bg-gray-50">
  @if (isAuthenticated()) {
    <!-- Sidebar desktop -->
    <aside class="hidden md:flex flex-col w-64 bg-gray-900 text-white fixed top-0 bottom-0 left-0">
      <!-- Logo -->
      <div class="flex items-center gap-2 p-5 border-b border-gray-700">
        <mat-icon class="text-blue-400">laptop_mac</mat-icon>
        <span class="font-bold text-lg">MacMarket Admin</span>
      </div>

      <!-- Nav -->
      <nav class="flex-1 px-3 py-4 space-y-1 overflow-y-auto">
        @for (item of visibleNav(); track item.path) {
          <a [routerLink]="item.path" routerLinkActive="bg-gray-700 text-white"
             class="flex items-center gap-3 px-3 py-2 rounded-lg text-gray-300 hover:bg-gray-800 hover:text-white transition-colors text-sm font-medium">
            <mat-icon class="text-sm">{{ item.icon }}</mat-icon>
            {{ item.label }}
          </a>
        }
      </nav>

      <!-- User -->
      <div class="p-4 border-t border-gray-700">
        <div class="flex items-center gap-3 mb-3">
          <div class="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center flex-shrink-0">
            <mat-icon class="text-sm">person</mat-icon>
          </div>
          <p class="text-sm text-gray-300 truncate">{{ userName() }}</p>
        </div>
        <button mat-stroked-button class="w-full text-gray-400 border-gray-600 text-xs" (click)="logout()">
          <mat-icon class="text-sm">logout</mat-icon>
          Déconnexion
        </button>
      </div>
    </aside>

    <!-- Mobile overlay -->
    @if (sidebarOpen()) {
      <div class="fixed inset-0 bg-black/50 z-40 md:hidden" (click)="closeSidebar()"></div>
      <aside class="fixed top-0 bottom-0 left-0 w-72 bg-gray-900 text-white z-50 flex flex-col">
        <div class="flex items-center justify-between p-4 border-b border-gray-700">
          <span class="font-bold text-lg">MacMarket Admin</span>
          <button mat-icon-button (click)="closeSidebar()" class="text-gray-400">
            <mat-icon>close</mat-icon>
          </button>
        </div>
        <nav class="flex-1 px-3 py-4 space-y-1">
          @for (item of visibleNav(); track item.path) {
            <a [routerLink]="item.path" routerLinkActive="bg-gray-700 text-white" (click)="closeSidebar()"
               class="flex items-center gap-3 px-3 py-2 rounded-lg text-gray-300 hover:bg-gray-800 hover:text-white transition-colors text-sm font-medium">
              <mat-icon class="text-sm">{{ item.icon }}</mat-icon>
              {{ item.label }}
            </a>
          }
        </nav>
      </aside>
    }
  }

  <!-- Main -->
  <div class="flex-1 flex flex-col min-w-0" [class.md:ml-64]="isAuthenticated()">
    @if (isAuthenticated()) {
      <!-- Mobile top bar -->
      <header class="md:hidden flex items-center justify-between h-14 px-4 bg-white border-b border-gray-200">
        <button mat-icon-button (click)="toggleSidebar()">
          <mat-icon>menu</mat-icon>
        </button>
        <span class="font-semibold">MacMarket Admin</span>
        <div class="w-10"></div>
      </header>
    }

    <!-- Page content -->
    <main class="flex-1 p-6">
      <router-outlet />
    </main>
  </div>
</div>
