// frontend-shop/src/components/layout/Footer.tsx
export function Footer() {
  return (
    <footer className="border-t bg-muted/40 py-8 mt-auto">
      <div className="container mx-auto px-4 text-center text-sm text-muted-foreground">
        <p>&copy; {new Date().getFullYear()} MacMarket. Tous droits reserves.</p>
        <p className="mt-1">Projet de demonstration — les produits ne sont pas a vendre.</p>
      </div>
    </footer>
  );
}

// frontend-shop/src/app/shared/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [RouterLink],
  template: `
    <footer class="border-t border-gray-200 mt-16 py-8">
      <div class="container mx-auto px-4 text-center text-sm text-gray-500">
        <p class="font-medium mb-1">MacMarket &copy; {{ year }}</p>
        <p>Le meilleur du Mac, au meilleur prix.</p>
      </div>
    </footer>
  `,
})
export class FooterComponent {
  readonly year = new Date().getFullYear();
}
